### ISSUE TITLE
C++11 raw string literals not supported

### ISSUE THREAD

**Issue by aroben** [textmate/c.tmbundle#22]
C++11 added a new raw string literal syntax. The C++ grammar in this bundle doesn't support it:

![screen shot 2014-11-21 at 4 03 12 pm](https://cloud.githubusercontent.com/assets/917945/5149561/f6c5500e-7197-11e4-88b7-d65440e93142.png)

You can also see this on github.com, which uses this bundle for highlighting C++ code: https://github.com/LegalizeAdulthood/ucpp-json-parser/blob/2bec48aa1edc40b5d1c82531b005818cb7f6dc53/json_test.cpp#L206. The bug was discovered by one of our users.

**Comment by Predelnik** [comment]
:+1: Also discovered this on github, would like to see fixed.
