### ISSUE TITLE
Syntax highlighting is wrong for regexp strings.

### ISSUE THREAD

**Issue by dezelin** [textmate/c.tmbundle#28]
Here is the file. There are two percent signs with red background, which is not correct:

https://github.com/dezelin/flang/blob/feature_ocaml_lexer/ocaml-llvm/include/ocamllexer.h

**Comment by sorbits** [comment]
We match printf-style placeholders in all strings, since we don’t know which functions actually take format strings, I don’t know how to selectively enable it, and consider the feature far too valuable to globally disable.

So won’t fix.
