### ISSUE TITLE
HIP support for sublime text

### ISSUE THREAD

**Issue by adityaatluri** [textmate/c.tmbundle#35]
Hi,
Before I start, HIP is an interface for running GPU code on both AMD and NVIDIA GPUs developed by AMD. Here is a [sample file](https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/blob/master/samples/0_Intro/square/square.hipref.cpp) I am trying to add HIP support for sublime through this repository because it uses .cpp extension. Will that be ok?

**Comment by sorbits** [comment]
As per the license of this bundle, you are free to do with it what you 
want.

**Comment by adityaatluri** [comment]
Hi,
Thanks. If I submit a pull request will that be merged?

**Comment by sorbits** [comment]
Would this be matching HIP-specific functions?

If so, I don’t think it belongs in the main C grammar.

Ideally it would be a HIP bundle that inject rules into the source.c 
scope then HIP users can install the bundle to get the added syntax 
highlight, but I think injection grammars is a TextMate-specific 
feature.

**Comment by adityaatluri** [comment]
Well, Yes. The grammar is specific to HIP. Such as \__global__< qualifiers. But these are being used in a .cpp file.

**Comment by sorbits** [comment]
Then I would not merge such a PR as the C bundle is for the core C language and additional support should be contained in their own bundles, either by injecting into source.c or by creating a new root grammar and include `source.c`.

**Comment by adityaatluri** [comment]
Thanks! :)
