### ISSUE TITLE
Some function names highlight in red with latest update

### ISSUE THREAD

**Issue by campbelljc** [textmate/c.tmbundle#70]
Hi there,

Since the bundle update of May 5, it appears that the names of some functions calls are being highlighted in red. See picture:

<img width="394" alt="Screen Shot 2020-05-13 at 10 02 29 PM" src="https://user-images.githubusercontent.com/174064/81884287-74adbc80-9565-11ea-92f9-d8937021f9c6.png">

If I replace the bundle with the previous version from the commit from last year (39898a8af42d2afa667ce5238e3765704d0d173e), the red highlight disappears.

Perhaps the gl functions are not in the 10.15 SDK?

**Comment by sorbits** [comment]
> Perhaps the gl functions are not in the 10.15 SDK?

It’s actually because these functions are deprecated (since macOS 10.14).

But I realize that this deprecation would only apply to (using) Apple’s implementation, and not the API itself, so I will change this shortly.

**Comment by campbelljc** [comment]
Great! Thanks :)
